/**
 * 用 esbuild 把后端 API 编译成单个 CJS 文件。
 * - 所有依赖内联（express, cors 等）
 * - 不打包 Node.js 内置模块（fs, path, http, child_process 等）
 * - 输出到 dist-server/server.cjs
 *
 * 这样 electron-builder 只需要把这个文件复制进去就行。
 */
import { build } from 'esbuild'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import fs from 'node:fs'

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const projectRoot = path.resolve(__dirname, '..')

const outDir = path.join(projectRoot, 'dist-server')
if (!fs.existsSync(outDir)) fs.mkdirSync(outDir, { recursive: true })

await build({
  entryPoints: [path.join(projectRoot, 'api', 'server.ts')],
  bundle: true,
  platform: 'node',
  target: 'node20',
  format: 'cjs',
  outfile: path.join(outDir, 'server.cjs'),
  external: [
    // Node.js 内置模块 — esbuild 会自动处理大部分，但显式列出来更保险
    'fs', 'path', 'os', 'http', 'https', 'url', 'querystring',
    'crypto', 'events', 'stream', 'util', 'buffer', 'assert',
    'constants', 'dns', 'net', 'tty', 'child_process',
  ],
  banner: {
    js: `// OI Training Log — bundled backend\n// DO NOT EDIT. Generated by scripts/build-server.mjs.\n`,
  },
  logLevel: 'info',
  minify: process.env.NODE_ENV === 'production',
})

const stat = fs.statSync(path.join(outDir, 'server.cjs'))
console.log(`✅ server.cjs 已生成 (${(stat.size / 1024).toFixed(1)} KB) → ${path.relative(process.cwd(), path.join(outDir, 'server.cjs'))}`)
